services:
    # This is a pseudo-service which simply tells compose to build all the depends_on projects
    all:
        image: busybox
        command: ["sleep", "5"]
        depends_on:
            - hello-world
            - basic-shapes
            - dvd-bounce
            - explorer
            - runtime-bf
            - runtime-lisp
            - runtime-lua
            - micro

    # The following are all services that build specific project executables
    hello-world: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/hello_world:/project/src 
    basic-shapes: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/basic_shapes:/project/src  
    dvd-bounce: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/dvd_bounce:/project/src  
    explorer: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/explorer:/project/src  
    
    runtime-bf: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/runtime_brainfk:/project/src  
    runtime-lisp: 
        build: 
            context: ./environment
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/runtime-tinylisp:/project/src  
    runtime-lua: 
        build: 
            context: ./environment
            dockerfile: ./Dockerfile.lua
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/runtime_lua:/project/src  

    micro: 
        build: 
            context: ./environment
            dockerfile: ./Dockerfile
        volumes:
        - ./bin:/project/bin
        - ./lib:/project/lib
        - ./projects/micro:/project/src  
