---
name: Test Build
on: push

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Podman
        uses: redhat-actions/podman-install@main
      - name: Start Podman Socket
        run: |
          podman system service --time=0 &
          sleep 2
      - name: Setup Podman Compose
        uses: webgtx/setup-podman-compose@v1
      - name: Build Projects
        run: podman compose -f compose.yml run --build --rm all