---
name: Test Build
on: push

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v6
      - name: Setup Podman
        uses: redhat-actions/podman-install@main
      - name: Start Podman Socket
        run: |
          podman system service --time=0 &
          timeout 30 bash -c 'until podman info > /dev/null 2>&1; do sleep 0.5; done'
      - name: Setup Podman Compose
        uses: webgtx/setup-podman-compose@v1
      - name: Build Projects
        run: podman compose -f compose.yml run --build --rm all & sleep 2